### PR TITLE
fix constraints form logic

### LINKED ISSUE #519: Change constraints panel logic to require one or more, not both
In "Set Constraints", the requirement before going to the next step is to either select/fill budget, OR fill treatment percentage, OR both. Right now, it requires for both to be selected/filled in.

image

### PR DESCRIPTION
**Pull request by thequeenofspades**
Fixes #519

### CODE REVIEW

File: src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts [hunk 1]
```diff
@@ -176,6 +184,18 @@ export class CreateScenariosComponent implements OnInit {
     });
   }
 
+  private constraintsFormValidator(constraintsForm: AbstractControl): boolean {
+    // Only one of budget or max treatment percentage is required.
+    const maxBudget = constraintsForm.get('budgetForm.maxBudget');
+    const optimizeBudget = constraintsForm.get('budgetForm.optimizeBudget');
+    const maxArea = constraintsForm.get('treatmentForm.maxArea');
+    console.log(constraintsForm.value);
+    console.log(
```
Comment (lattemilk) [inline src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts:193]: are we intentionally keeping the logs for now?

**Review by lattemilk — APPROVED** [review]

File: src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts (hunk 1 above)
Comment (thequeenofspades) [reply src/interface/src/app/plan/create-scenarios/create-scenarios.component.ts]: haha nope, thanks for catching!
