### PR TITLE
Display detail card for all boundaries and projects at clicked point on map

### LINKED ISSUE #126: Mouse click popup information is layer-order dependent and prevents user from exploring lower levels
==== Issue Description & Steps to Reproduce ====

Provided the demo presented on Fri Nov 18, 2022, the popup that appears when mouse clicks on the map will showcase information about the top-most layer. For example, if user: 
1) turns on "Projects" layer
2) turns on "HUC"
3) clicks on the map where there's an overlap between HUC and a project polygon

Then information about the HUC will appear. The reverse is true if steps 1 and 2 are flipped.

==== Expected Outcome ====

It is necessary for the user to be able to explore all layers on given coordinates. ArcGIS does this by showing all related information in the same popup with clickable next arrows, each layer OR polygon (there can be multiple overlapping polygons from the same layer) representing each card.

### PR DESCRIPTION
**Pull request by thequeenofspades**
## Changes
- Added hover states for boundary and project polygons on map.
- Added tooltip displaying project name for project polygons on map.
- When the user clicks on a point on the map, a detail card pops up containing info for **every** feature overlapping that point, not just the feature in the topmost layer. This excludes the region layer.
- Unit tests.
- Fixes #126 

## Screenshot (detail card popup)
image

## Screenshot (boundary hover state)
Screen Shot 2022-12-12 at 2 19 10 PM

## Screenshot (project hover state)
image

### CODE REVIEW

**Review by lattemilk — APPROVED** [review]

File: src/interface/src/app/map/project-card/project-card.component.ts [hunk 1]
```diff
@@ -1,13 +1,77 @@
-import { Component, Input } from '@angular/core';
+import { Component, Input, OnInit } from '@angular/core';
 import { Feature, Geometry } from 'geojson';
 
+interface Boundary {
+  shape_name: string;
+}
+
+interface Project {
+  PROJECT_NAME?: string;
```
Comment (lattemilk) [inline src/interface/src/app/map/project-card/project-card.component.ts:9]: is there a reason why these are all capitalized?

Comment (thequeenofspades) [reply src/interface/src/app/map/project-card/project-card.component.ts:9]: Not sure, it's how they're coming from the backend (and I assume straight from CalMapper). JSON is case-sensitive so we'd have to convert each of these fields if we wanted to use typical camel case.
